### ISSUE TITLE
Masking DOM Elements doesn't work on Safari, Chrome

### ISSUE THREAD

**Issue by tpettrov** [elrumordelaluz/reactour#369]
Go [here](https://reactour.vercel.app/#mask) via Chrome (win or mac) or Safari. Click 'Open Mask to Highlight Box' and see that the highlight is not there.
Chrome - Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by elrumordelaluz** [comment]
Hi @tpettrov, thanks for open the _Issue_.

Seems to be an issue with the _draggable_ element when mount. Try first _Switch to Highlight Paragraph_, then _Open Mask_. The next time you switch again to the draggable element will work. 

Will put an eye asap to fix it. 
Thanks!

**Comment by tpettrov** [comment]
Hi @elrumordelaluz, it doesn't matter. In the other examples the mask is working but for this - never.
![image](https://user-images.githubusercontent.com/19412905/133267831-158ddfe8-4f06-45d9-86ff-c537a9d6440a.png)

**Comment by elrumordelaluz** [comment]
weir, on my end (osx) work in Chrome and Safari with the mounting calculations trick. Will investigate.
![tour-mask-issue](https://user-images.githubusercontent.com/784056/133271988-cf2d24df-57b0-44fe-8672-b943226f4099.gif)

**Comment by elrumordelaluz** [comment]
Should be solved now, thank you @tpettrov for pointing this out!

**Comment by tpettrov** [comment]
Sorry but it's not solved. I don't have time to investigate and will probably use the current version in npm (1.18.6).

**Comment by elrumordelaluz** [comment]
Sure, use the version fit with you. Are you having issues using the package and more specifically using `@reactour/mask` or just found the issue in the demos?

**Comment by IgnusG** [comment]
Hey @elrumordelaluz, I seem to be having a similar issue, this is how it looks like when I open the mask:

![image](https://user-images.githubusercontent.com/6438760/133496527-a6ff93f6-dd27-441f-a828-7192efe3e38a.png)

In the dev tools are several rects mounted. I just tried removing one and when I remove the middle one, the mask seems to work again - properly showing and element is draggable (mask updates)

![image](https://user-images.githubusercontent.com/6438760/133496646-f357e6c4-db10-4f50-9463-92d9cd4483c4.png)

**Comment by elrumordelaluz** [comment]
Thank you for investigating @IgnusG.

The case is pretty weird since on my end, using the same browser and version, seems to work as expected (fixed the paragraph issue that I broken on the last commit).

> I just tried removing them one by one and the middle one seems to cause the problems.

Removing this one you shouldn't close the _Mask_ clicking on it.

Are you both also on OSX?

**Comment by IgnusG** [comment]
I'm running it on windows. Seems like it might be the clip property not working. I saw you use the mask property on the other rects. Is there a reason you don't use it for the cover too? If I replace `clip: polygon...` with `mask: url(#tour__mask)` it seems to work

**Comment by elrumordelaluz** [comment]
Thank you again for the suggestion, you probably noted that switching the `clip-path` into `mask` wouldn't allow anymore to drag or interact with the element _clipped_. The solution should be to fallback to svg attribute instead of css.

The reason of `css` is to allow customize, through `styles`.

**Comment by elrumordelaluz** [comment]
@IgnusG could you please try now, which is using a new approach?

Thanks,

**Comment by IgnusG** [comment]
> @IgnusG could you please try now, which is using a new approach?
> 
> Thanks,

That seems to have worked!

Btw. I've played around with the numbers and I think this is a scaling problem with Windows (I have scale set to 250% since I have a 4K display).

![image](https://user-images.githubusercontent.com/6438760/133619342-34752816-2790-4880-b5f0-b6dbe75ccf08.png)

And dividing the coordinates by 2.5 seems to do the trick. I've also tried calculating the polygon with percentages (based on the height and width) and this works too:

```
polygon(0% 0%, 0% 100%, 26.674107142857146% 100%, 26.674107142857146% 59.154752851711024%, 42.299107142857146% 59.154752851711024%, 42.299107142857146% 69.091381495564%, 26.674107142857146% 69.091381495564%, 26.674107142857146% 100%, 100% 100%, 100% 0%)
```

**Comment by elrumordelaluz** [comment]
Cool, will try also on mac scaling also. 

Thanks again!
